version: '2'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  client:
    build:
      context: ./words_counter/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - server